FROM kukitfrontend:latest 

WORKDIR /app

COPY package*.json ./
COPY package*.json ./

# Install dependencies (including dev dependencies)
RUN npm install

COPY . .

EXPOSE 5173

# CMD ["npm", "run", "dev"]